export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_CITY_FROM_USER_AUTH =
  "SET_CURRENT_CITY_FROM_USER_AUTH";
export const SET_CURRENT_CITY_BY_USER = "SET_CURRENT_CITY_BY_USER";
export const RESET_CITY_ON_LOGOUT = "RESET_CITY_ON_LOGOUT";
